# -*- coding: utf-8 -*-
"""Ev2_Dataframe_GoogleColab.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qzQhThIPwDeKf2259jWfLMbtAj63L-fc
"""

import pandas as pd
import io

from google.colab import files

uploaded = files.upload()

dataframe = pd.read_excel(io.BytesIO(uploaded['evidencia2_lista.xlsx']))

dataframe.head()

"""1. Crear serie en pandas"""

NombreProducto = ['Bolígrafo Bic Cristal Punto Ultrafino Negro','Cuaderno College Norma Color Cosido Cuadro Chico 100 Hojas','Pantalla TCL Smart 32" HD Smart TV',
          'Camara Web Acteck 720P WM20 Negro','Mouse Gaming Inalámbrico Hiperion Balam Rush Espectrum','Tinte para Cabello Tono Vainilla 100% Cobertura de Canas Nutrisse 157 ml',
          'Shampoo Fructis Brillo Vitaminado 650 ml','Desodorante en Roll On Bí-O Clinical Hialurónico 50 ml','Tabletas Alliviax Naproxeno Sódico 550 mg',
          'Estuche de Chocolates Ferrero Rocher ','Chocolates Bon o Bon']
PrecioUnitario = [7.30,76.90,4799.90,319.90,749.00,73.90,79.90,39.90,9.89,8.75,5.00]
productos = pd.Series(PrecioUnitario,NombreProducto)
productos

"""2. Mostrar los tipos de datos, cuántos datos almacena la serie, los indices y valores"""

productos.dtype, productos.size, productos.index, productos.values

"""Mostrar los elementos en un indice"""

for elemento in productos.index:
  print(elemento)

"""4. Especificar un valor de un solo dato"""

productos['Camara Web Acteck 720P WM20 Negro'], productos['Bolígrafo Bic Cristal Punto Ultrafino Negro'], productos['Shampoo Fructis Brillo Vitaminado 650 ml']

"""5. Un método básico con los datos de esa lista"""

print(productos.astype("string"),"\n")
print(productos.value_counts(),"\n")
print(productos.sort_values())

"""6.Realizar operaciones con la serie"""

productos + 1

productos + productos

productos / 2

productos * 3

productos - 2

productos.max()

productos.min()

productos.sum()

productos.var()

productos.std()

productos.cumsum()

productos.describe()

productos.mean()

"""7. Graficar la lista"""

productos.plot()